//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop_Business.CoffeeShopService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoffeeShopService.ICoffeeShopService")]
    public interface ICoffeeShopService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoffeeShopService/GetData", ReplyAction="http://tempuri.org/ICoffeeShopService/GetDataResponse")]
        CoffeeShop_Models.CoffeeMenuModel[] GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoffeeShopService/GetData", ReplyAction="http://tempuri.org/ICoffeeShopService/GetDataResponse")]
        System.Threading.Tasks.Task<CoffeeShop_Models.CoffeeMenuModel[]> GetDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoffeeShopServiceChannel : CoffeeShop_Business.CoffeeShopService.ICoffeeShopService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoffeeShopServiceClient : System.ServiceModel.ClientBase<CoffeeShop_Business.CoffeeShopService.ICoffeeShopService>, CoffeeShop_Business.CoffeeShopService.ICoffeeShopService {
        
        public CoffeeShopServiceClient() {
        }
        
        public CoffeeShopServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoffeeShopServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoffeeShopServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoffeeShopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CoffeeShop_Models.CoffeeMenuModel[] GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<CoffeeShop_Models.CoffeeMenuModel[]> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
    }
}
